### ISSUE TITLE
Explore the campus map

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#10]
**EPIC 1: Explore the Campus Map**

This epic consists of multiple stories which map to the following requirements:

- Support both SGW and Loyola maps
- Make shapes for the campus buildings, so that they are easily distinguished from the city buildings
- Be able to easily switch between the campuses (toggle button)
- Show the building I am currently located in
- Show additional information for each building (pop-up information)

**Comment by AlainJobs** [comment]
I think this is done. @mohanadarafe If it's done, close this issue. 🥇
