### ISSUE TITLE
Spike: indoor maps

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#108]

**Comment by mohanadarafe** [comment]
# General information

- SVG files have a `<path>` tag which is used to draw lines.

- We can use the following component to make our indoor map [zoom-able](https://github.com/Alanaktion/react-native-zoomable-image)

- We will need to draw all possible walking paths, identify classrooms, water fountains & bathrooms in the SVG file h8.svg provided

- I found this [SVG selector](https://github.com/hugozap/react-svgmt) that allows us to modify the file 

# The plan

1. Upon zooming in, the `<MapView>` should become the inside map. @csbduzi @badred123 were working on this.
2. Add the` h8.svg` file inside the `Zoomable `component we found.
3. Add correct markers inside the floor map **by modifying the XML file.**
4. Mark up all classes, bathrooms, water fountains, escalators & more using this [drawer](https://editor.method.ac/)
5. Draw walkable paths (opacity 0 to not show them)
6. Using python, we will modify the XML to up the opacity to 1 if the path is needed to be displayed (through a path finding algorithm)

**Comment by csbduzi** [comment]
Does the algorithm have to be written in the python? It may seem excessive in a react-native project...could it be written in JavaScript?

**Comment by AlainJobs** [comment]
In the **Plan** subsection, your first point : _Upon zooming in, the <MapView> should become the inside map (...)._  Do you have any idea how? Because this is quite vague... Will it be a second screen or everything is on the <MapView>?

**Comment by csbduzi** [comment]
For the zooming in, I had open a spike issue, to see how we would display another "screen" after a specific zoom level...so are we still going with another screen?

**Comment by bkenza** [comment]
When you say "_The algorithm starts at S & asks if it can go up, left, down or right_" does this mean that we are tracking the user location? And if so, will it be accurate enough indoors?

**Comment by mohanadarafe** [comment]
> Does the algorithm have to be written in the python? It may seem excessive in a react-native project...could it be written in JavaScript?

@csbduzi Not per say, but parsing the XML & modifying it would require python (as we did in 345). But, we can do it using JS as well with [xmldom](https://github.com/jindw/xmldom)

> In the **Plan** subsection, your first point : _Upon zooming in, the should become the inside map (...)._ Do you have any idea how? Because this is quite vague... Will it be a second screen or everything is on the ?

@AlainJobs As Chris said, once the MapView delta is under value x, we switch to inside screen display


> When you say "_The algorithm starts at S & asks if it can go up, left, down or right_" does this mean that we are tracking the user location? And if so, will it be accurate enough indoors?

No, S can be a classroom and E can be a bathroom. We do not need the user location (since we can't do it inside a map). This is a situation where a user selects his starting and ending location.

**Comment by mohanadarafe** [comment]
Update!

### Shortest Path Algorithm
I decided to go with Dijkstra's shortest path algorithm. It's widely known & easy to implement. Our graph consists of a data file which has all classrooms listed & their neighbour. So, for example, classroom H855 would have H853 & H857 as neighbours in the graph.

### Where to Go Algorithm
I also saw the need to implement a where to go algorithm. This contains three scenarios:
1) Same floor directions
2) Different floor directions
3) Leave building directions
