### ISSUE TITLE
In the more info screen, the image takes some time to load. (2-3 sec)

### ISSUE THREAD

**Issue by badred123** [mohanadarafe/GuideMe#110]

**Comment by csbduzi** [comment]
I would replace this bug label by a "performance issue" since the the functionality is actually working

**Comment by AlainJobs** [comment]
I don't think we can focused on this issue any longer. It is out of control and might be fixed by itself once we have release. @bkenza If you agree, please close this issue 💯

**Comment by bkenza** [comment]
I do agree with @AlainJobs. We will be closing this issue due to time constraints!
