### ISSUE TITLE
Outdoor Points of Interest (coffee shops, restaurants, etc.)

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/GuideMe#12]
EPIC 5: Outdoors Points of Interest (coffee shops, restaurants, etc.)

This epic consists of multiple stories which map to the following requirements:

a. Show the nearest X (or based on a range) outdoor points of interest
b. Show directions to a selected outdoor point of interest

**Comment by AlainJobs** [comment]
## Update
The outdoor point of interest is only restricted to restaurants for the sake of this project.
