### ISSUE TITLE
Spike: Implement a design pattern.

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#122]

**Comment by bkenza** [comment]
This article is great for this: https://hackernoon.com/react-native-effective-patterns-3e0c9db6c32c

It seems like we have most of the react native design patterns down, although implementing Redux might be a good idea? What do you think @AlainJobs?

**Comment by AlainJobs** [comment]
> This article is great for this: https://hackernoon.com/react-native-effective-patterns-3e0c9db6c32c
> 
> It seems like we have most of the react native design patterns down, although implementing Redux might be a good idea? What do you think @AlainJobs?

Sorry I didn't see this message earlier. And I think we are better off without redux.
