### ISSUE TITLE
Improve search bar suggestions collapse functionality

### ISSUE THREAD

**Issue by Firassawan** [mohanadarafe/GuideMe#127]
Current behaviour: 

- A user selects the search bar from the home page. 
- The search bar is populated with suggestions of surrounding buildings.
- The user is stuck there and forced to select one of the options (or type something) in order to collapse the search bar suggestions. 
- clicking on the "enter" button collapses the suggestions but is a unclear for an uninformed user.

Possible Improvement: 
- Clearly indicate how the user can collapse the search bar function. 
- Perhaps clicking on the map to the side would be the best option to exist the suggestion view.

**Comment by bkenza** [comment]
Due to time contraints, we will be closing this enhancement issue.
