### ISSUE TITLE
Find an end-to-end testing framework

### ISSUE THREAD

**Issue by JayChouteau** [mohanadarafe/GuideMe#131]
It seems that with Jest and Enzyme, we are limited to unit/component/integration testing. All we can do is mocking or isolating parts of the code to test those self-contained parts. We can't perform system (end-to-end) testing very well. We need to find a way to cover End-to-end testing. Here are some of the possible solutions:
- Appium
- Detox
- Calabash

I would personally go with Calabash since it uses Cucumber for writing scenarios (BDD) and will make it really easy to understand what the test scenarios cover for anyone looking at the tests. Also, Cucumber can be integrated well with Jest and Enzyme. This needs further investigation and fast as we need to implement system testing.

**Comment by JayChouteau** [comment]
Here is a reference for different react-native automation testing tools depending on the stage of testing:
https://www.smashingmagazine.com/2016/08/test-automation-frameworks-for-react-native-apps/

**Comment by bkenza** [comment]
We have already tried integrating Detox into the project. However, it was incompatible with Travis CI and we could not make it work. You can see a list of commits related to this issue in the following branch:
https://github.com/mohanadarafe/GuideMe/commits/kenza :)

**Comment by JayChouteau** [comment]
After a more in-depth analysis of Calabash and an attempt to integrate into our framework, it seems that Calabash has 2 different frameworks: Calabash-IOS and Calabash-Android. Since we are developing and testing mainly on IOS at the moment, we tried integrating Calabash-IOS. However, there is an issue since we need to run the code (app) on Xcode in order to integrate this automated e2e testing framework. To do so, we would have to eject our project onto xcode (from vscode/expo) and change all of the dependencies of our code which would be tedious. This solution might not be the best in our current react-native js ran through expo application.

**Comment by JayChouteau** [comment]
About Appium:
it seems that most of the literature agrees to state that using Appium as an e2e testing framework is tedious, complicated and cumbersome. Basically, not recommended.

**Comment by JayChouteau** [comment]
Overall, here are the conclusions for e2e automated testing from our research so far:
- e2e testing for React Native apps on expo is difficult and relatively new
- e2e testing frameworks for React Native apps on expo are either complicated and tedious to implement/ integrate or they have strong limitations.
- Platform-specific testing frameworks such as Earl Grey and Espresso are more stable, but cross-platform frameworks are harder to integrate possess more limitations/risks to use them
-  Among the different cross-platform options that seem the most simple and/or most suited to our application, the best option seems to be Detox (with the limitations mentioned above), followed by Cavy (still needs further investigation).

**Comment by AlainJobs** [comment]
The teacher accepted a local end-to-end testing. What we did in Detox can be re-open and Cavy is being investigated. 🔢

**Comment by csbduzi** [comment]
Just as @JayChouteau had mentionned, among the cross-platform end-to-end testing framework, Cavy seemed like the most simple one to implement into the project for e2e testing on iOS and Android simulators. After further investigation into Cavy, the end-to-end testing framework has no specific indication that it is compatible with an Expo bundle. My suggestion would be to stick with our primary option, which is Detox.
