### ISSUE TITLE
Cut Off of Labels in the Bottom Menu

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/GuideMe#138]
**Label Issue**

Long strings that are passed as Building Names in the Bottom Menu are cut off because of the width of the label. 

**Path to fix this are:** 
- Resize the label when displaying a long string 
- Add three dots on at the end of the end string when too long 
- Show only the initial or reduce the keywords in the data files

**Comment by AlainJobs** [comment]
What happened with this bug, any updates?
