### ISSUE TITLE
Implementation of Route Preview + Preference Screen 

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/GuideMe#139]
### General Information 

- The route preview screen is a screen that will display a preview path from one point to another between two makers on a outdoor map. 

- The preview screen will be accompanied of a bottom menu that will display the important information such as the method of transportation and the time to arrival to get to the destination.

- From the bottom menu, there will be an arrow-up button, where the user will have the option to press on it, to make the preference page appear.

- On the preference page, the user will have the option to choose from transportation method, pick the type of user that represents him/her and indicate whether his/her mobility is reduced for appropriate accommodation. By changing those settings, the traced route on the outdoor map or on the indoor building map will change accordingly.

**Comment by AlainJobs** [comment]
Preference Menu has implemented properly. As of now, we can't fetch the value to the Preview Screen.

**Comment by csbduzi** [comment]
The preferences screen has been implemented with a simple and  unencrypted key-value storage (AsyncStorage) for the persistence and retrieval of values by other screens. The buttons on the **PreferenceMenu** will have states and whenever a change is recorded by the AsyncStorage, the **PreviewDirection** screen will be be able to retrieve the values of the buttons.

Here is a sneak peek of the Preference Screen:

**Comment by bkenza** [comment]
Fixed via #171
