### ISSUE TITLE
Switch case disappear after pressing on a building

### ISSUE THREAD

**Issue by bloulidi** [mohanadarafe/GuideMe#147]
**Label Issue**

The switch case only exists in the bottom menu when the user does not click on any building/class. There is no way to get it back after that. 

**Path to fix this are:**

- When you click on the map, the selection is removed and the bottom menu gets back to the view with the switch

**Comment by bkenza** [comment]
Issue moved to Sprint 4!

**Comment by AlainJobs** [comment]
Fixed it on redux branch. Will be referenced in my PR.
