### ISSUE TITLE
Acceptance Test #1 | US26: As a user, I would like to be able to set a room as my start or destination point

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#152]
### Story
As a user, I would like to be able to set a room as my start or destination point

### Steps to reproduce
1. Open the app
2. Press on the search bar
3. Query a classroom
4. Press on _Get Directions_ in the bottom menu
5. Change starting or ending point

**Note: current supported classrooms are H5XX & H8XX**

### Preview
![us26](https://user-images.githubusercontent.com/34899555/77170472-768d5f00-6a91-11ea-863b-4201b776aa25.gif)

**Comment by jodavimehran** [comment]
This user story is similar to #178. You should merge them together.
