### ISSUE TITLE
Acceptance Test #2 | US31: As a user, I would like to be able to generate directions to rooms between floors.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#153]
### Story
As a user, I would like to be able to generate directions to rooms between floors.

### Steps to reproduce
1. Open the app
2. Press on the search bar
3. Query a classroom
4. Press on _Get Directions_ in the bottom menu
5. Enter a **from** classroom
6. Enter a **to** classroom
7. Press on the arrow back
8. Press on the Hall Building inside the map
9. Press on _Get Inside_ in the bottom menu
10. Navigate to the floors you have queried directions for

**Note: current supported classrooms are H5XX & H8XX**

### Preview
![us31](https://user-images.githubusercontent.com/34899555/77171295-a0935100-6a92-11ea-8a95-853e7e8517fb.gif)

**Comment by jodavimehran** [comment]
Why the app force user to follow the 7th step to the 10th step, while there is the View Route button in the step 6th?

**Comment by mohanadarafe** [comment]
> Why the app force user to follow the 7th step to the 10th step, while there is the View Route button in the step 6th?

@jodavimehran Good question. The reason why is because we do not have the mixture of both indoor & outdoor directions together. Currently, directions are mutually exclusive. In sprint 4, we will do all directions with the View Route button.

**Comment by jodavimehran** [comment]
Ok, good.

Just discriminate the start point and the endpoint in the indoor direction UI and also add an arrow to the path line to show the direction of movement.
