### ISSUE TITLE
Acceptance Test #3 | US12: As a user, I want to be able to select a destination building by clicking on it.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#154]
### Story
As a user, I want to be able to select a destination building by clicking on it.

### Steps to reproduce
1. Open the app
2. Tap on a building of your choice
3. Press on _Get Inside_ in the bottom menu
4. Press on _Get Directions_ 
5. The **to** field is the building you selected

### Preview
![us12](https://user-images.githubusercontent.com/34899555/77172206-fcaaa500-6a93-11ea-9722-ddaa951d1505.gif)

**Comment by jodavimehran** [comment]
This user story is similar to #178. You should merge them together.
