### ISSUE TITLE
Acceptance Test #4 | US37: As a user, I would like to navigate through building floors

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#155]
### Story
As a user, I would like to navigate through building floors.

### Steps to reproduce
1. Open the app
2. Press on building of choice
3. Press on _Get Inside_ in the bottom menu
4. Navigate through floors using the bottom selector

**Note: current supported buildings are Hall & JMSB, the other buildings use the Hall SVG by default**

### Preview
![us37](https://user-images.githubusercontent.com/34899555/77172866-0bde2280-6a95-11ea-9687-101755fd6724.gif)

**Comment by jodavimehran** [comment]
accepted
