### ISSUE TITLE
Acceptance Test #5 | US14: As a user, I should be able to set my current position as the starting point.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#156]
### Story
As a user, I should be able to set my current position as the starting point.

### Steps to reproduce
1. Open the app
2. Press on the search bar
3. Query a destination
4. Press on _Get Directions_ in the bottom menu
5. The **default starting point** is the user's current location

### Preview
![ezgif-1-4ef918b318d2](https://user-images.githubusercontent.com/34899555/77176387-60d06780-6a9a-11ea-9008-a7470a52b131.gif)

**Comment by jodavimehran** [comment]
This user story is similar to #178. You should merge them together.
