### ISSUE TITLE
Add the permission for Location in the CurrentBuildingLocation file 

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/GuideMe#163]
To solve this issue, add permission for Location in the CurrentBuildingLocation file

![image](https://user-images.githubusercontent.com/46238950/77222574-e4d23000-6b2a-11ea-94f8-6cda8230a23a.png)

**Comment by AlainJobs** [comment]
## Update, this is caused by _CurrentBuildingLocation_ component and should be moved to the refactor.
