### ISSUE TITLE
Acceptance Test #8 | US16: As a user, I would like to be able to be given directions between campuses

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#179]
### Story
As a user, I would like to be able to be given directions between campuses.

### Steps to reproduce
1. Start the application
2. Tap on a search bar & query "Hall" then select _Hingston Hall, Wing HB_ (or any Loyola building)
3. Click on _Get Directions_ in the bottom menu
3. Click on Starting Position & query _Hall_ then select henry F. Hall Building (or any SGW building)
4. Click on View Route

### Preview
![jure](https://user-images.githubusercontent.com/34899555/77563814-24d14400-6e98-11ea-962e-a3c27007c0e1.gif)

**Comment by jodavimehran** [comment]
This user story is similar to #178. You should merge them together.
