### ISSUE TITLE
Acceptance Test #9 | US15: As a user, I want to be able to view directions on the map

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#180]
### Story
As a user, I would like to be able to be given directions between classes from two different campuses.

### Steps to reproduce
1. Start the application
2. Tap on a search bar & query any building of choice
3. Click on _Get Directions_ in the bottom menu
3. Click on Starting Position & query any building of choice
4. Click on View Route
5. Click on Start
6. Click on the right arrow button for next instructions

### Preview
![Animated GIF-downsized_large](https://user-images.githubusercontent.com/33582344/77288490-571f4d80-6cae-11ea-9b79-548bdc410dd4.gif)

**Comment by jodavimehran** [comment]
Accepted
