### ISSUE TITLE
Acceptance Test #11 | US19: As a user, I should be able to choose public transport as a means of transportation.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#182]
### Story
As a user, I should be able to choose public transport as a means of transportation.

### Steps to reproduce
1. Start the application
2. Tap on a search bar & query any building of choice
3. Click on _Get Directions_ in the bottom menu
3. Click on Starting Position & query any building of choice
4. Click on View Route
5. Click on the upper arrow in the bottom menu
6. Select Transit in Method of Travel
7. Click on the bottom arrow at the top of the screen
8. Press on refresh

### Preview
![bus](https://user-images.githubusercontent.com/34899555/77566928-c490d100-6e9c-11ea-90d6-c11978b5a646.gif)

**Comment by jodavimehran** [comment]
Accepted
