### ISSUE TITLE
Acceptance Test #7 [bug & solution]

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/GuideMe#189]
### Required csv
[BUILDING_LIST.zip](https://github.com/mohanadarafe/GuideMe/files/4411125/BUILDING_LIST.zip)

### Description
As reported by the PO (see screenshot), some buildings are not found in the algorithm that fetches the coordinates. This is due to the inconsistency of the _BuildingData.js_ structure. In fact, the method in DoubleSearch checks for the name of a specific building thinking that the key name of that building is the same as the building's official name. Although it is true for most buildings, for some it is not. 
**Examples: ** 
- _LB Building_ is the key name of the _JW McConnell Building_
### Solution
I will attach a csv that contains all the info regarding buildings. We are focused on two fields in that csv : _BuildingName_ and _Building Long Name_. To fix the issue, we need to go on **_BuildingData.js_** and 
1. add a field called _fullName_ for every building that is the value of _Building Long Name_ from the csv.
2. Replace the field _name_  by the value _BuildingName_  from the csv.

![image](https://user-images.githubusercontent.com/33582344/78065410-41babb00-7361-11ea-8657-0d376656f4dd.png)

To see how to reproduce this bug, see #178 and the comments.
### Screenshot
![image](https://user-images.githubusercontent.com/33582344/78064742-3024e380-7360-11ea-94c1-77a76585f567.png)

**Comment by AlainJobs** [comment]
The bug is still on master... I didn't run the PR I assumed it everything was working fine since you detailed that in the description. So I'll fix the inconsistencies.

**Comment by bkenza** [comment]
Fixed via #192
