### ISSUE TITLE
Double search bar screen displays departement and services

### ISSUE THREAD

**Issue by badred123** [mohanadarafe/GuideMe#203]
When you are inside of the double search bar screen, you should not be able to search for departement and services. They are not destinations.

**How to reproduce the bug**

1. Open the app
2. Choose a destination and click get directions
3. Inside the double search bar screen, choose a departement as a starting or end destination
4. Click getDirections
5. Observe the issue

**Comment by AlainJobs** [comment]
## Update
I'm allowing the user to search for the services and departments now. It's going to find the right building.
