### ISSUE TITLE
Change the placeholder color to grey when the user wants to write (DoubleSearchBar)

### ISSUE THREAD

**Issue by bloulidi** [mohanadarafe/GuideMe#204]
When i am inside the double search bar screen and i want to change the text inside the fields, I felt that some things were not great for the UX. First, when i click on the text displayed inside the search bar it does not disapear. I tried to remove it with "backspace" but it didn't want to. Because of that, i though that the text was still inside and i couldn't remove it. However, i realized that if i start writing, the new text started appearing.

**Comment by bkenza** [comment]
@badred123 so after a discussion with the PO, we said that we would keep it as black for the time being. If we want it to be grey, the **`to`** field should not be editable.
