### ISSUE TITLE
Acceptance Test #1 | US-21: As a user, I would like to view the Concordia shuttle bus schedule for both campuses. [SPRINT 4]

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#229]
### Story
As a user, I would like to view the Concordia shuttle bus schedule for both campuses.

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Shuttle Bus in the side menu

### Preview
![image](https://user-images.githubusercontent.com/35609559/79271638-20cc8c80-7e6e-11ea-8d06-ccacc2942884.png)

**Comment by jodavimehran** [comment]
Accepted
