### ISSUE TITLE
Acceptance Test #2 | US-24 As a user, I would like to find the location of a classroom from the next calendar event. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#230]
### Story
As a user, I would like to find the location of a classroom from the next calendar event.

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Settings
4. Toggle the _Google Calendar Sync_ switch
5.  Log into your Google Account. In case the app is deemed not safe, click on _Advanced_ & _Go to GuideMe_ options to log in.
6. Select the calendar you want to sync
7. Press on the side menu (hamburger icon)
8. Go to Course Schedule
9. Select the class/event you want to find the the location of

### Preview
![ezgif-4-46c736e0515b](https://user-images.githubusercontent.com/34899555/79644600-01887480-8178-11ea-9731-0d99831ff456.gif)

**Comment by jodavimehran** [comment]
Accepted
