### ISSUE TITLE
Acceptance Test #3 | US-22 As a user, I would like to connect my direction to next class to my google calendar. [SPRINT 4]

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#231]
### Story
As a user, I would like to find the location of a classroom from the next calendar event.

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Settings
4. Toggle the _Google Calendar Sync_ switch
5.  Log into your Google Account. In case the app is deemed not safe, click on _Advanced_ & _Go to GuideMe_ options to log in.
6. Select the calendar you want to sync
7. Press on the side menu (hamburger icon)
8. Go to Course Schedule
9. Select the class you want to go to
10. Click on View Route

### Preview
![ezgif-4-3d4e42201c69](https://user-images.githubusercontent.com/34899555/79644649-457b7980-8178-11ea-92bb-5cf16ae2b7c7.gif)

**Comment by jodavimehran** [comment]
Accepted
