### ISSUE TITLE
Acceptance Test #4 |  US-29 As a user, I would like to show paths optimized for access by students with disabilities. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#232]
### Story
As a user, I would like to show paths optimized for access by students with disabilities.

### Steps to reproduce
1. Open the app
2. Search for a classroom
3. Press on Get Directions
4. Select the starting point as a classroom in a different floor (ex: H5 to H8)
5. You will notice the default route is the closest stairs.
6 Press on the upper icon in the bottom menu
7. Select **YES** for **Mobility Reduced** & slide down the preference menu.
8. The path is now optimized to take the elevator.

### Preview
![ezgif-4-62665026725a](https://user-images.githubusercontent.com/34899555/79644882-c9823100-8179-11ea-9b68-caaf7205b40f.gif)

**Comment by jodavimehran** [comment]
Accepted
