### ISSUE TITLE
Acceptance Test #5 | US-30 As a user, I would like to be able to highlight points of interest such as washrooms, water foundations, stairs, etc. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#233]
### Story
As a user, I would like to be able to highlight points of interest such as washrooms, water foundations, stairs, etc.

### Steps to reproduce
1. Open the app
2. Inside the search screen, search from a classroom to an Indoor POI (Men's Washroom, Women's Washroom, Water Fountain)
3. Press on View Route

### Preview
![ezgif-4-ea997c3098cd](https://user-images.githubusercontent.com/34899555/79668675-8ed1c600-8184-11ea-96a5-a313fb978a34.gif)

**Comment by jodavimehran** [comment]
Accepted
