### ISSUE TITLE
Acceptance Test #7 | US-33 As a user, I would like to be able to be given directions between classes from two different campuses. [SPRINT 4]

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#234]
### Story
As a user, I would like to be able to be given directions between classes from two different campuses.

### Steps to reproduce
1. Open the app
2. Search for a classroom (H5XX, H8XX, H9XX, VL103)
3. Press on Get Directions
4. Select the starting point as a classroom in a different campus (**NOTE: the only supported classroom in Loyola is VL103**)
5. Press on Get Directions
6. After getting directions inside, press on Exit Building
7. Navigate your way to your destination
8. At the last instruction, a yellow building icon pops up, click on it
9 It leads you to the inside of the building for the rest of the directions

### Preview
![ezgif-4-a5ea938b6022](https://user-images.githubusercontent.com/34899555/79645200-d011a800-817b-11ea-8dc5-de6d279fc931.gif)

**Comment by jodavimehran** [comment]
Accepted
