### ISSUE TITLE
Acceptance Test #8 | US-34 As a user, I would like to see the nearest outdoor points of interest. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#236]
### Story
As a user, I would like to see the nearest outdoor points of interest. 

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Points of Interests

### Preview
![ezgif-4-569745521e26](https://user-images.githubusercontent.com/34899555/79661977-72cd2500-8182-11ea-8ffb-4aed06e75935.gif)

**Comment by jodavimehran** [comment]
Accepted
