### ISSUE TITLE
Acceptance Test #9 | US-35 As a user, I would like to get the direction to the chosen nearest point of interest. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#237]
### Story
As a user, I would like to get the direction to the chosen nearest point of interest.

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Points of Interests
4. Select a point of interest
5. Press on _Get Directions_
6. Press on _View Route_

### Preview
![ezgif-4-e8d72d789e86](https://user-images.githubusercontent.com/34899555/79663163-cb042700-8182-11ea-8447-f3eab94a1000.gif)

**Comment by jodavimehran** [comment]
Accepted
