### ISSUE TITLE
Acceptance Test #10 |  US-36 As a user, I would like to see a detailed description of the selected places. [SPRINT 4] 

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#238]
### Story
As a user, I would like to see a detailed description of the selected places. 

### Steps to reproduce
1. Open the app
2. Open the side menu by pressing on the hamburger menu in the search bar
3. Press on Points of Interests
4. Select a point of interest

### Preview
![ezgif-4-7bf20fa5ce59](https://user-images.githubusercontent.com/34899555/79664086-0e5e9580-8183-11ea-8491-cde90ca4840a.gif)

**Comment by jodavimehran** [comment]
Accepted
