### ISSUE TITLE
US26 - As a user, I would like to be able to set a particular room as my start or destination point.

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#35]
The user should be able to set any room as from the indoor maps as their start position or destination point prior to displaying a navigation route.

**Comment by mohanadarafe** [comment]
Isn't this done on sprint 2 in the search bar? @bkenza

**Comment by bkenza** [comment]
@mohanadarafe no, this issue means that you can set a room as your start/destination point in the second search screen (the one with the two search bar)
