### ISSUE TITLE
Fix Travis CI build.

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#87]
The Travis CI build continuously fails (after integrating Detox). The issue lies in the configuration of the **before_script**.

All tests pass **locally**.

**To reproduce bug:**

1. Install Detox
	brew/tap wix/brew
	brew install applesimutils
	npm install  -g detox-cli
	npm install detox --save-dev

2. Add the following configuration to the project’s package.json file

"detox": {
  "configurations": {
    "ios.sim.debug": {
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/example.app",
      "build": "xcodebuild -project ios/example.xcodeproj -scheme example -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11 Pro"
      }
    }
  }
}

3. Run the command:
	detox init -r jest

4. Create a system UI test inside the generated e2e test directory:

5. In the Map.js file, add testID = “mapview” to the View surrounding the MapView tag

6. Run the test
		npm test

7. Push the changes into GitHub and the build should fail

**Comment by mohanadarafe** [comment]
Can you add the steps to reproduce please?
