### ISSUE TITLE
Application has UI and functionality inconsistencies (iOS, Android)

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/GuideMe#93]
This image summarizes the issues we are currently facing in regard to running the app on both android and iOs. 
**Update: ** 
- The app works as expected on iOS. (**Good**)
- _The app doesn't work as expected on iOS_

![compteRendu](https://user-images.githubusercontent.com/33582344/75404038-58d83a00-58d7-11ea-80ca-028ee12d8e96.jpg)

**Comment by bkenza** [comment]
Issue moved to Sprint 3.

**Comment by bkenza** [comment]
due to time contraints, we will be closing this issue as it is very low priority.
